#!/usr/bin/env python3
"""Render the doc sections that restate a rule, straight from the code.

A design doc that quotes a payoff is a second copy of that payoff, and this repo
has now watched that copy go stale twice over: the game design doc carried the v8
table into a v11 game, and the platform design doc described a 10x10 match long
after the game shipped 7x5. Guard tests caught neither, because the first guard
written for them asserted "this exact string appears" — which turns a silent
drift into a loud one but still leaves a human retyping the number by hand.

So the blocks below are GENERATED. Each one sits between HTML comment markers in
its markdown file and is written by a function that reads the constants. Nobody
edits inside the markers; you change `rules.py` and re-run this. The prose
AROUND each block is hand-written and stays that way — the doc's job is the why,
and the code's job is the what.

Usage:
    python scripts/render_generated_docs.py            # check; non-zero if stale
    python scripts/render_generated_docs.py --write    # rewrite the blocks

`tests/test_generated_doc_blocks_are_current.py` runs the check in CI.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT: Path = Path(__file__).resolve().parents[1]
# Needed only for the `python scripts/render_generated_docs.py` invocation, where
# the repo root is not already importable. Under pytest it is a no-op.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from app.games import get as get_game_module  # noqa: E402
from app.games.hoard_hurt_help.rules import (  # noqa: E402
    DEFAULT_MUTUAL_HELP_MODE,
    MutualHelpMode,
    mutual_help_value,
)

BEGIN = "<!-- BEGIN GENERATED: {id} -->"
END = "<!-- END GENERATED: {id} -->"
# Printed inside every block so a reader who lands on one mid-file knows not to
# edit it, without having to find this script first.
BANNER = (
    "<!-- Generated by scripts/render_generated_docs.py from the code. "
    "Do not edit by hand — change the constants and re-run. -->"
)


def _demote_headings(markdown: str, *, levels: int = 2) -> str:
    """Push every ATX heading down `levels`, for embedding inside a doc.

    The rules text is a standalone document with its own `#` title. Dropped into
    a section of a bigger doc it would open a second top-level heading and break
    the outline, so the embed shifts it. Presentation only — no wording changes,
    which is the point: the text stays the one the agents are served.
    """
    out = []
    for line in markdown.splitlines():
        stripped = line.lstrip("#")
        depth = len(line) - len(stripped)
        out.append("#" * (depth + levels) + stripped if depth else line)
    return "\n".join(out)


def hoard_hurt_help_rules() -> str:
    """The full Hoard-Hurt-Help rulebook, as agents are served it.

    This is deliberately the SAME text the agent reads, not a doc-only retelling:
    `semantic_rules_text` is already the one rendering of the constants, and a
    second one written for humans is exactly the copy this script exists to
    remove. Rendered with no arguments, so it shows what the game currently
    ships rather than any one match's settings.
    """
    return _demote_headings(get_game_module("hoard-hurt-help").semantic_rules_text())


def mutual_help_modes() -> str:
    """Every mutual-help mode and what a pact pays each side under it.

    The rulebook above states only the mode a match is played on. The design doc
    needs all five side by side to explain why the default moved, so this renders
    them from `mutual_help_value` — the same function the resolver pays out of.
    """
    first = "the pair's first time"
    rows = {
        MutualHelpMode.FLAT_6: "{v} every time",
        MutualHelpMode.FLAT_7: "{v} every time",
        MutualHelpMode.FLAT_8: "{v} every time",
        MutualHelpMode.DECAY: (
            "{v} " + first + ", then -1 per repeat down to a floor of {floor}. "
            "A fresh partner resets to {v}. Counted per pair, match-wide."
        ),
        MutualHelpMode.NO_REPEATS: (
            "{v}, unless that same pair also mutually helped on the PREVIOUS "
            "turn, which pays the plain {repeat}. A one-turn cooldown, not a "
            "lifetime cap."
        ),
    }
    lines = ["| Mode | What a pact pays each side |", "|---|---|"]
    for mode, shape in rows.items():
        label = f"`{mode.value}`"
        if mode is DEFAULT_MUTUAL_HELP_MODE:
            label += " — **the default for a new match**"
        detail = shape.format(
            v=mutual_help_value(mode, 0),
            floor=mutual_help_value(mode, 99),
            repeat=mutual_help_value(mode, 0, repeated_last_turn=True),
        )
        lines.append(f"| {label} | {detail} |")
    return "\n".join(lines)


def shipped_match_shape() -> str:
    """The match shape, for the platform doc's per-turn-payload section.

    Platform-level prose should not hardcode a game's numbers at all, but this
    section illustrates the payload with real values, so it renders them.
    """
    cfg = get_game_module("hoard-hurt-help").config_defaults()
    total = cfg.total_rounds * cfg.turns_per_round
    return (
        f"The shipped Hoard-Hurt-Help match is **{cfg.total_rounds} rounds of "
        f"{cfg.turns_per_round} turns** ({total} turns total), "
        f"**{cfg.min_players}-{cfg.max_players} players**, on rules "
        f"**{get_game_module('hoard-hurt-help').rules_version()}**. Every count "
        f"is admin-configurable per match; these are what `config_defaults()` "
        f"returns."
    )


@dataclass(frozen=True)
class Block:
    doc: str
    block_id: str
    render: Callable[[], str]


BLOCKS: tuple[Block, ...] = (
    Block(
        "docs/games/hoard-hurt-help/HOARD_HURT_HELP_DESIGN.md",
        "hoard-hurt-help-rules",
        hoard_hurt_help_rules,
    ),
    Block(
        "docs/games/hoard-hurt-help/HOARD_HURT_HELP_DESIGN.md",
        "mutual-help-modes",
        mutual_help_modes,
    ),
    Block(
        "docs/platform/AGENT_LUDUM_DESIGN.md",
        "shipped-match-shape",
        shipped_match_shape,
    ),
)


def block_body(block: Block) -> str:
    """What must sit between this block's markers, banner included."""
    return f"{BANNER}\n\n{block.render().strip()}"


def _marker_span(text: str, block: Block) -> tuple[int, int]:
    """Where this block's content starts and ends in `text`.

    Raises rather than skipping: a doc that lost its markers is a doc that
    silently stopped being generated, which is the failure this whole script
    exists to prevent.
    """
    begin, end = BEGIN.format(id=block.block_id), END.format(id=block.block_id)
    i = text.find(begin)
    j = text.find(end)
    if i < 0 or j < 0:
        raise ValueError(
            f"{block.doc} is missing the {'begin' if i < 0 else 'end'} marker for "
            f"block {block.block_id!r}. Re-add {begin if i < 0 else end!r} — the "
            f"block cannot be rendered without it."
        )
    if j < i:
        raise ValueError(f"{block.doc}: {block.block_id!r} markers are out of order.")
    return i + len(begin), j


def current_and_expected(block: Block) -> tuple[str, str]:
    """This block as the file has it, and as the code says it should be."""
    text = (REPO_ROOT / block.doc).read_text()
    start, stop = _marker_span(text, block)
    return text[start:stop].strip(), block_body(block).strip()


def write_block(block: Block) -> bool:
    """Rewrite one block in place. True when the file changed."""
    path = REPO_ROOT / block.doc
    text = path.read_text()
    start, stop = _marker_span(text, block)
    updated = f"{text[:start]}\n{block_body(block)}\n{text[stop:]}"
    if updated == text:
        return False
    path.write_text(updated)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write", action="store_true", help="rewrite the blocks instead of checking"
    )
    args = parser.parse_args()

    stale: list[Block] = []
    for block in BLOCKS:
        if args.write:
            changed = write_block(block)
            print(f"{'updated' if changed else 'unchanged'}  {block.doc}  [{block.block_id}]")
        else:
            have, want = current_and_expected(block)
            if have != want:
                stale.append(block)
                print(f"STALE  {block.doc}  [{block.block_id}]")
    if stale:
        print(
            f"\n{len(stale)} generated block(s) are out of date. Run:\n"
            f"    python scripts/render_generated_docs.py --write",
            file=sys.stderr,
        )
        return 1
    if not args.write:
        print(f"all {len(BLOCKS)} generated blocks are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
